<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qiDlCDz' shared service.

return $this->privates['.service_locator.qiDlCDz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'beneficiaire' => ['privates', '.errored..service_locator.qiDlCDz.App\\Entity\\Beneficiaire', NULL, 'Cannot autowire service ".service_locator.qiDlCDz": it references class "App\\Entity\\Beneficiaire" but no such service exists.'],
], [
    'beneficiaire' => 'App\\Entity\\Beneficiaire',
]);
