<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TK.y_1E' shared service.

return $this->privates['.service_locator.TK.y_1E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'beneficiaireRepository' => ['privates', 'App\\Repository\\BeneficiaireRepository', 'getBeneficiaireRepositoryService.php', true],
], [
    'beneficiaireRepository' => 'App\\Repository\\BeneficiaireRepository',
]);
