<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cJl82u9' shared service.

return $this->privates['.service_locator.cJl82u9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'UtilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
    'Utilisateurs' => ['privates', '.errored..service_locator.cJl82u9.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.cJl82u9": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'UtilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
    'Utilisateurs' => 'App\\Entity\\Utilisateur',
    'entityManager' => '?',
]);
