<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ojhUcTA' shared service.

return $this->privates['.service_locator.ojhUcTA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'transaction' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
], [
    'entityManager' => '?',
    'transaction' => 'App\\Repository\\TransactionRepository',
]);
