<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SLRTBSE' shared service.

return $this->privates['.service_locator.SLRTBSE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'expediteurRepository' => ['privates', 'App\\Repository\\ExpediteurRepository', 'getExpediteurRepositoryService.php', true],
], [
    'expediteurRepository' => 'App\\Repository\\ExpediteurRepository',
]);
