<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XLk6Yrn' shared service.

return $this->privates['.service_locator.XLk6Yrn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'expediteur' => ['privates', '.errored..service_locator.XLk6Yrn.App\\Entity\\Expediteur', NULL, 'Cannot autowire service ".service_locator.XLk6Yrn": it references class "App\\Entity\\Expediteur" but no such service exists.'],
], [
    'expediteur' => 'App\\Entity\\Expediteur',
]);
