<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1KBa8Au\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1KBa8Au/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1KBa8Au.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1KBa8Au\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1KBa8Au\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1KBa8Au',
    'container.build_id' => '4c81cd9e',
    'container.build_time' => 1566049723,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1KBa8Au');
