<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6fBPAWf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6fBPAWf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6fBPAWf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6fBPAWf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6fBPAWf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6fBPAWf',
    'container.build_id' => '127711b5',
    'container.build_time' => 1571910992,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6fBPAWf');
